version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes
    ports:
      - "5433:5432"

  recipes:
      image: immortal/recipes
      environment:
          POSTGRES_HOST: host.docker.internal
      ports:
          - "8080:8080"
      extra_hosts:
          - host.docker.internal:host-gateway